language: python

python:
  - "2.7"
  - "2.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install --fix-broken --ignore-missing -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" swig
  - pip install http://dl.dropbox.com/u/174789/m2crypto-0.20.1.tar.gz
  - pip install salt

install:
  - pip install -q -e .
  - pip install -q python-coveralls rednose

script: python manage.py test --rednose --with-coverage --cover-package=stretch

after_success:
  - coveralls
